CREATE SCHEMA
IF NOT EXISTS parser;
SET SCHEMA=parser;
CREATE TABLE
    IF NOT EXISTS parser.locations
    (
        id        INT generated BY DEFAULT AS IDENTITY PRIMARY KEY,
        locId     VARCHAR(32) UNIQUE,
        locName   VARCHAR(255),
        trackType VARCHAR(32),
        locLength VARCHAR(32)
    );
CREATE TABLE
    IF NOT EXISTS parser.cars
    (
        id         INT generated BY DEFAULT AS IDENTITY PRIMARY KEY,
        carId      VARCHAR(255) UNIQUE,
        roadName   VARCHAR(255),
        roadNumber VARCHAR(255)
    );
CREATE UNIQUE INDEX
    IF NOT EXISTS parser.carReport
ON
    parser.cars
    (
        roadname,
        roadnumber
    );
CREATE TABLE
    IF NOT EXISTS parser.runIds
    (
        id           INT generated BY DEFAULT AS IDENTITY PRIMARY KEY,
        runId        VARCHAR(16) UNIQUE,
        COMMENT      VARCHAR(255),
        created_date TIMESTAMP
    );
CREATE TABLE
    IF NOT EXISTS parser.seq_value
    (
        id          INT generated BY DEFAULT AS IDENTITY PRIMARY KEY,
        current_seq INT
    );
CREATE TABLE
    IF NOT EXISTS parser.run_locs
    (
        id      INT generated BY DEFAULT AS IDENTITY PRIMARY KEY,
        runid   VARCHAR(16),
        seq_num INT,
        carId   VARCHAR(255),
        locid   VARCHAR(32),
        load    VARCHAR(255),
        FOREIGN KEY(runid) REFERENCES parser.runIds (runId) ON
DELETE
    NO ACTION ,
    FOREIGN KEY(locId) REFERENCES parser.locations(locId)
ON
DELETE
    NO ACTION,
    FOREIGN KEY(seq_num) REFERENCES parser.seq_value(current_seq)
ON
DELETE
    NO ACTION,
    FOREIGN KEY(carId) REFERENCES parser.cars(carId)
ON
DELETE
    NO ACTION
    );
    
    