CREATE SCHEMA
IF NOT EXISTS parser;
SET SCHEMA=parser;
CREATE TABLE
    IF NOT EXISTS parser.locations
    (
        id        INT generated BY DEFAULT AS IDENTITY PRIMARY KEY,
        locId     VARCHAR(32) UNIQUE,
        locName   VARCHAR(255),
        trackType VARCHAR(32),
        locLength VARCHAR(32)
    );
CREATE TABLE
    IF NOT EXISTS parser.cars
    (
        id         INT generated BY DEFAULT AS IDENTITY PRIMARY KEY,
        carId      VARCHAR(255) UNIQUE NOT NULL,
        roadName   VARCHAR(255) NOT NULL,
        roadNumber VARCHAR(255) NOT NULL
    );
CREATE UNIQUE INDEX
    IF NOT EXISTS parser.carReport
ON
    parser.cars
    (
        roadname,
        roadnumber
    );
CREATE TABLE
    IF NOT EXISTS parser.runIds
    (
        id           INT generated BY DEFAULT AS IDENTITY PRIMARY KEY,
        runId        VARCHAR(16) UNIQUE NOT NULL,
        comments     VARCHAR(255),
        created_date TIMESTAMP
    );
CREATE TABLE
    IF NOT EXISTS parser.seq_value
    (
        id          INT generated BY DEFAULT AS IDENTITY PRIMARY KEY,
        current_seq INT NOT NULL,
        runId       VARCHAR(16) UNIQUE NOT NULL
    );
CREATE TABLE
    IF NOT EXISTS parser.run_locs
    (
        id      INT generated BY DEFAULT AS IDENTITY PRIMARY KEY,
        runid   VARCHAR(16) NOT NULL,
        seq_num INT NOT NULL,
        carId   VARCHAR(255) NOT NULL,
        locid   VARCHAR(32) NOT NULL,
        load    VARCHAR(255) NOT NULL,
        UNIQUE( runid, carId, locId),
        FOREIGN KEY ( runid ) REFERENCES parser.runIds ( runId ) ON
DELETE
    NO ACTION ,
    FOREIGN KEY(locId) REFERENCES parser.locations(locId)
ON
DELETE
    NO ACTION,
    FOREIGN KEY(seq_num) REFERENCES parser.seq_value(current_seq)
ON
DELETE
    NO ACTION,
    FOREIGN KEY(carId) REFERENCES parser.cars(carId)
ON
DELETE
    NO ACTION 
    )
    ;
INSERT INTO
    runids
    (
        RunId,
        comments,
        Created_Date
    )
    VALUES
    (
        'A',
        'First test',
        CURRENT_TIMESTAMP
    );
UPDATE
    runids 
SET 
    comments = 'Value'
WHERE 
    runId = 'A';
INSERT INTO
    seq_value
    (
        current_seq,
        runid
    )
    VALUES
    (
        1,
        'A'
    );
    UPDATE 
    seq_value
SET 
    current_seq = 1
WHERE 
    runid = 'A';
    SELECT 
    COUNT(*) 
FROM 
    seq_value 
WHERE 
    runId = 'A';
