set schema = parser;
CREATE TABLE
    IF NOT EXISTS locations
    (
        id       INT generated BY DEFAULT AS IDENTITY PRIMARY KEY,
        runid    VARCHAR(32) NOT NULL,
        xmlid    VARCHAR(32),
        name     VARCHAR(255) NOT NULL,
        trkCount INT NOT NULL DEFAULT 0,
        UNIQUE (runid, xmlid)
    );
CREATE TABLE
    IF NOT EXISTS tracks
    (
        id          INT generated BY DEFAULT AS IDENTITY PRIMARY KEY,
        parentId    INT NOT NULL,
        parentxmlid VARCHAR(32) NOT NULL,
        trkId       VARCHAR(32),
        trkName     VARCHAR(255),
        trackType   VARCHAR(32),
        trkLength   VARCHAR(32),
        runId       VARCHAR(16),
        UNIQUE (runId, trkId),
        FOREIGN KEY (runid, parentId) REFERENCES locations (runid, id)
    );
CREATE TABLE
    IF NOT EXISTS cars
    (
        id         INT generated BY DEFAULT AS IDENTITY PRIMARY KEY,
        carId      VARCHAR(255) NOT NULL,
        roadName   VARCHAR(255) NOT NULL,
        roadNumber VARCHAR(255) NOT NULL,
        carLoad    VARCHAR(255),
        runId      VARCHAR(16),
        UNIQUE (runid, carid),
        UNIQUE (runid, roadname, roadnumber)
    );
CREATE TABLE
    IF NOT EXISTS runIds
    (
        id           INT generated BY DEFAULT AS IDENTITY PRIMARY KEY,
        runId        VARCHAR(16) UNIQUE NOT NULL,
        comments     VARCHAR(255),
        seqNum       INT NOT NULL,
        created_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    );
CREATE TABLE
    IF NOT EXISTS run_locs
    (
        id      INT generated BY DEFAULT AS IDENTITY PRIMARY KEY,
        runid   VARCHAR(16) NOT NULL,
        seq_num INT NOT NULL,
        carId   VARCHAR(255) NOT NULL,
        trkid   VARCHAR(32) NOT NULL,
        load    VARCHAR(255) NOT NULL,
        UNIQUE(runid, seq_num, carId),
        UNIQUE(runid, seq_num, trkid, carId),
        FOREIGN KEY ( runid ) REFERENCES runIds ( runId ) ON
DELETE
    NO ACTION ,
    FOREIGN KEY(runid, trkId) REFERENCES tracks(runid, trkId)
ON
DELETE
    NO ACTION,
    FOREIGN KEY(runid, carId) REFERENCES cars(runid, carId)
ON
DELETE
    NO ACTION
    );
    
    

