CREATE TABLE
    IF NOT EXISTS locations
    (
        id        INT generated BY DEFAULT AS IDENTITY PRIMARY KEY,
        locId     VARCHAR(32),
        locName   VARCHAR(255),
        trackType VARCHAR(32),
        locLength VARCHAR(32),
        runId      VARCHAR(16),
        Unique  (runId, locId)
    );
CREATE TABLE
    IF NOT EXISTS cars
    (
        id         INT generated BY DEFAULT AS IDENTITY PRIMARY KEY,
        carId      VARCHAR(255) NOT NULL,
        roadName   VARCHAR(255) NOT NULL,
        roadNumber VARCHAR(255) NOT NULL,
        carLoad    VARCHAR(255),
        runId      VARCHAR(16),
        UNIQUE (runid, carid),
        UNIQUE (runid, roadname, roadnumber)
    );
CREATE TABLE
    IF NOT EXISTS runIds
    (
        id           INT generated BY DEFAULT AS IDENTITY PRIMARY KEY,
        runId        VARCHAR(16) UNIQUE NOT NULL,
        comments     VARCHAR(255),
        created_date TIMESTAMP
    );
CREATE TABLE
    IF NOT EXISTS seq_value
    (
        id          INT generated BY DEFAULT AS IDENTITY PRIMARY KEY,
        current_seq INT NOT NULL,
        runId       VARCHAR(16) UNIQUE NOT NULL
    );
CREATE TABLE
    IF NOT EXISTS run_locs
    (
        id      INT generated BY DEFAULT AS IDENTITY PRIMARY KEY,
        runid   VARCHAR(16) NOT NULL,
        seq_num INT NOT NULL,
        carId   VARCHAR(255) NOT NULL,
        locid   VARCHAR(32) NOT NULL,
        load    VARCHAR(255) NOT NULL,
        UNIQUE( runid, seq_num, carId, locId),
        FOREIGN KEY ( runid ) REFERENCES runIds ( runId ) ON
DELETE
    NO ACTION ,
    FOREIGN KEY(locId) REFERENCES locations(locId)
ON
DELETE
    NO ACTION,
    FOREIGN KEY(carId) REFERENCES cars(carId)
ON
DELETE
    NO ACTION 
    );
    
    

